config/routes.rb
Rails.application.routes.draw do

  mount_activeadmin_settings()

  get 'items/add_to_favorites'
  get 'items/remove_from_favorites'
  get 'items/clear_favorites'

  devise_for :admin_users, ActiveAdmin::Devise.config

  ActiveAdmin.routes(self)

  namespace :admin do
    resources :items do
      collection do
        get :add_all_generations
      end
    end

    resources :catalogs do
      collection do
        get :manage
        post :rebuild
      end
    end
  end

  get 'test/index'
  root 'catalogs#index'
  resources :receptions
  resources :items
  resources :pages
  resources :posts
  resources :item_attachments
  resources :catalogs do
    collection do
      resources :autos do
        resources :items
      end
    end
    resources :autos do
      resources :items
    end
  end

end

app/models/admin_user.rb
class AdminUser < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable

  attr_accessible :email, :password, :password_confirmation
end

app/models/auto.rb
class Auto < ActiveRecord::Base

  has_many :generations
  belongs_to :brand

  attr_accessible :name, :color, :car_image, :manhour, :brand_id, :item_ids

  default_scope { order('brand_id ASC') }
  scope :by_auto, -> auto { where(:brand_id => auto) }

  validates :name, :brand_id, :presence => true


  # scope :vw, where('brand.name = Volkswagen')
  # scope :vw, -> { joins(:brand).where(brand: { name: 'Film Maker' }) }

  # def all_vw
  #   Auto.find(:all, conditions: {:category_id => '1'})
  # end



end

app/models/auto_item.rb
class AutoItem < ActiveRecord::Base

  belongs_to :auto
  belongs_to :item

  attr_accessible :auto_id, :item_id, :partial_price

end

app/models/brand.rb
class Brand < ActiveRecord::Base

  has_many :autos

  attr_accessible :name, :image, :image_32, :color

  validates :name, :image, :image_32, :presence => true

end

app/models/catalog.rb
class Catalog < ActiveRecord::Base

  # def self.default_scope
    # Should return a scope, you can call 'super' here etc.
    # order('position DESC')
  # end

  acts_as_nested_set

  include TheSortableTree::Scopes

  has_many :items

  attr_accessible :name, :parent_id

  attr_protected :lft, :rgt

  validates :name, :parent_id, :presence => true

  # scope :autos_items, -> (id) {where('catalogs.depth' => 0).order(:lft) | includes(items: :autos).where('autos_items.auto_id' => id).order(:lft)}

  scope :autos_items, -> (id) {includes(items: :autos).where('autos_items.auto_id' => id).order(:lft)}

  scope :subcat, -> (cat) {where('parent_id' => cat.id).order('lft ASC')}

  # scope :john_smith, lambda { where(:name => "John") | where(:lastname => "Smith")


end

app/models/catalogs_items.rb
class CatalogsItems < ActiveRecord::Base
end

app/models/generation.rb
class Generation < ActiveRecord::Base

  belongs_to :auto
  has_many :generation_items
  has_many :items, through: :generation_items

  validates :name, :auto_id, presence: true

  attr_accessible :auto_id, :name, :manhour

  default_scope { order('auto_id ASC') }

end

app/models/generation_item.rb
class GenerationItem < ActiveRecord::Base

  belongs_to :generation
  belongs_to :item

  attr_accessible :generation_id, :item_id, :install_hours, :dop_price

  # default_scope { includes(generation: :auto).order('auto_id ASC') }

  # validates :generation_id, :presence => true

end

app/models/item.rb
class Item < ActiveRecord::Base

  default_scope { order('position asc') }

  scope :promo, where(old_price: '')

  has_many :item_attachments
  has_many :properties
  has_many :generation_items
  has_many :generations, through: :generation_items
  belongs_to :catalog

  accepts_nested_attributes_for :properties, :allow_destroy => true
  accepts_nested_attributes_for :generations
  accepts_nested_attributes_for :item_attachments, :allow_destroy => true
  accepts_nested_attributes_for :generation_items, :allow_destroy => true

  attr_accessible :name, :description, :install_hours, :price, :old_price, :partial_price, :catalog_id, :generation_ids, :generation_items_attributes, :property_ids, :properties_attributes, :item_attachments_attributes, :keywords, :position

  # validates :catalog_id, :name, :

  acts_as_list

  scope :without_category, {
      :joins      => "LEFT JOIN catalogs_items ON items.id = catalogs_items.item_id",
      :conditions => "catalogs_items.item_id IS NULL"
  }

  def self.search(search)
    unless search.blank?
      sss = search
      Item.where('LOWER(name) LIKE ?', "%#{sss}%") | where('LOWER(description) LIKE ?', "%#{sss}%") | joins(:generations).where('LOWER(generations.name) LIKE ?', "%#{sss}%")
    else
      all
    end
  end



end

app/models/item_attachment.rb
class ItemAttachment < ActiveRecord::Base

  mount_uploader :image, ImageUploader
  belongs_to :item

  attr_accessible :item_id, :image, :remove_image

end

app/models/menu.rb
class Menu < ActiveRecord::Base

  acts_as_list

  attr_accessible :title, :url, :published, :position

  default_scope -> {order('position ASC')}

end

app/models/page.rb
class Page < ActiveRecord::Base

  attr_accessible :title, :intro, :full, :published, :alias

  validates_uniqueness_of :alias

end

app/models/post.rb
class Post < ActiveRecord::Base

  attr_accessible :title, :body, :published

end

app/models/property.rb
class Property < ActiveRecord::Base

  belongs_to :item

  attr_accessible :item_id, :name, :value

  validates :name, :value, presence: true

end

app/models/reception.rb
class Reception < ActiveRecord::Base

  attr_accessible :name, :email, :phone, :theme, :message

  validates :name, :email, :message, presence: true

  validates_format_of :email, :with => /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\z/i

end

app/helpers/autos_helper.rb
module AutosHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/test_helper.rb
module TestHelper
end

app/views/layouts/admin.html.slim
doctype
  html
    head
      = favicon_link_tag '/favicon.ico'
      meta name="viewport" content="width=device-width, height=device-height, initial-scale=1.0, user-scalable=0, minimum-scale=1.0, maximum-scale=1.0, user-scalable=no"
      / title
        - unless yield(:title).blank?
          = yield(:title)
          '  ||
        ' Официальный сайт МОСКВОРЕЧЬЕ-САБУРОВО
      = stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true
      = javascript_include_tag "application", "data-turbolinks-track" => true
      = stylesheet_link_tag    "admin/admin", :media => "all"
      = csrf_meta_tags
      link href="//netdna.bootstrapcdn.com/font-awesome/4.0.3/css/font-awesome.css" rel="stylesheet"

    body
      .container
        = yield

app/views/layouts/application.html.slim
doctype
html
  head
    = favicon_link_tag '/favicon.ico'
    title = content_for?(:title) ? content_for(:title) : settings_value('Название сайта').value
    meta name='description' content='#{content_for?(:description) ? content_for(:description) : settings_value('Описание').value}'
    meta name='keywords' content='#{content_for?(:keywords) ? content_for(:keywords) : settings_value('Ключевые слова').value}'
    meta name="viewport" content="width=device-width, height=device-height, initial-scale=1.0, user-scalable=0, minimum-scale=1.0, maximum-scale=1.0, user-scalable=no"
    = stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true
    = javascript_include_tag "application"
    = csrf_meta_tags
    link href="//netdna.bootstrapcdn.com/font-awesome/4.0.3/css/font-awesome.css" rel="stylesheet"
    link href='http://fonts.googleapis.com/css?family=Roboto+Condensed:300&subset=latin,cyrillic' rel='stylesheet' type='text/css'

  body
    .container
      #notice_message
        .col-md-12
          .alert.alert-success
            button type="button" class="close" data-dismiss="alert" aria-hidden="true" &times;
            p.t-c
      = render 'partials/header'
      .row
        .col-md-4
          = render 'partials/catalog'
          = render 'partials/widget_last_news'
          = render 'partials/widget_last_viewed'
          = render 'partials/widget_favorites'
        .col-md-8
          = yield
    br
    = render 'partials/footer'
    = render 'partials/reception'
    = javascript_include_tag "anijs"
    = javascript_include_tag "anijsscrollreveal"

app/views/pages/index.html.slim
h1 Pages#index
p Find me in app/views/pages/index.html.slim

app/views/pages/show.html.slim
/.row
/
/  .col-md-4
/
/    = render partial: 'partials/catalog', locals: {xxx: @catalogs_all, catalog_index: true}
/    = render partial: 'partials/widget_last_viewed'
/
/  .col-md-8

- if admin_user_signed_in?
  h4.pull-left
    =' best_in_place @page, :title, :type => :input, :path => [:admin, @page]
    span: sub-header.text-muted> #{@page.published ? '(опубликовано)' : '(НЕ ОПУБЛИКОВАНО!!!)'}

  a.pull-right href='#{edit_admin_page_url(@page)}'
    .btn.btn-danger.btn-xs.pull-right Редактировать
  .clearfix
  hr
  p.t-j = @page.full

- else
  h4.pull-left = @page.title
  .clearfix
  hr
  p.t-j = @page.full

app/views/partials/_catalog.html.slim
#catalog
  .fadeInRight.animated
    - if @auto
      table#auto-image style='border-right: 10px solid ##{@auto.brand.color};'
        tr
          td width='100%'
            a data-anijs='if: mouseover, do: pulse animated' href='#{auto_url(@auto)}'
              = image_tag @auto.car_image, :class => 'pull-left auto-img fadeInRight animated'
          td
            a href='#{auto_url(@auto)}'
              =' image_tag @auto.brand.image_32, class: 'brand-32'
          td
            a href='#{auto_url(@auto)}' style='text-decoration: none; color: #333'
              h3.auto_name
                b = @auto.name

      hr


    h4.pull-left Каталог
    .pull-right style='margin-top: 10px;'
      small: a#collaps_in.is_tooltip.pointer  title='Развернуть'
        i.fa.fa-plus-square style='font-size: 14px'
      span<> |
      small: a#collaps.is_tooltip.pointer  title='Свернуть'
        i.fa.fa-minus-square style='font-size: 14px'
    .clearfix

    .panel-group#accordion
      - if @catalogs_all.any?
        - @catalogs_all.each_with_index do |cat, i|

          #menu-row

            /= params
            - if ( controller_name == 'autos' && params[:id] ) || ( params[:auto_id] && params[:id] )
              - children = Catalog.includes(items: :generations).where('parent_id' => cat.id, 'generations.auto_id' => params[:auto_id] ? params[:auto_id] : params[:id] ).order('lft ASC')
            - else
              - children = Catalog.includes(items: :generations).where('parent_id' => cat.id).order('lft ASC')

            - if children.any? && cat.depth == 0
              h5#header-cat data-toggle="collapse" data-parent="#accordion" href="#collapse-#{cat.id}"
                i.indicator.fa.fa-plus-square-o> style='font-size: 13px'
                =' cat.name


            .panel-collapse.collapse id='collapse-#{cat.id}' class='depth-#{cat.depth+1}' data-collapspanel=''

              - children.each do |sub|
                div
                  span.fa.fa-angle-double-right>
                  a.catalog_link href='#{controller_name=='autos' ? catalog_auto_url(sub.id, params[:id]) : catalog_url(sub.id)}'
                    =' sub.name

                - if Catalog.subcat(sub).any?
                  div class='depth-#{cat.depth+1}'
                    - Catalog.subcat(sub).each do |sub_sub|
                      div
                        span.fa.fa-angle-double-right>
                        a.catalog_link href='#{catalog_url(sub.id)}'
                          =' sub_sub.name

app/views/partials/_favorites.html.slim
#favorites class='#{'hidden' if session[:favorite_items].blank?}'
  hr
  h4 Избранное
  table
    - if !session[:favorite_items].blank?
      - session[:favorite_items].try(:each) do |item|
        - item = Item.find(item)
        tr id='item_row-#{item.id}' valign="middle"
          td: a.remove_from_favorites remote='true' href='javascript:void(0)' data-item='#{item.id}': img.small-img height='40' src="#{item.item_attachments.any? ? item.item_attachments.first.image.small_thumb : '/assets/item_no_image.png'}"
          td: small: a href='#{item_path(item)}': small = item.name

app/views/partials/_footer.html.slim
br
#footer.visible-lg
  .container
    .row
      .col-md-7#menu
        table width='100%'
          tr
            td
              a.menu-link href='#{root_url}'
                = image_tag('logo-mini.png')
            - Page.all.each do |page|
              td
                a.menu-link href='#{page_url(page)}' = page.title
      .col-md-5
        .pull-right
          h3 style='margin-top: 13px;'
            span> style='font-size: 15px'
              span.fa.fa-phone.fa-lg>
              |+7 (967)
            |121-5-212
          h6.t-r style='margin: 0': small
            'Обновление системы от
            = l @settings['version']['date']

app/views/partials/_header.html.slim
br
.row#brands
  .col-md-4.t-c
    /  a.cool2 href='#{root_url}'
    /    = image_tag('logo.png', :id => 'logo', :'data-anijs' => 'if: mouseover, do: pulse animated')
    /- else
    /- unless controller_name == 'autos'
    a.cool2 href='#{root_url}'
      = image_tag 'logo.png', :id => 'logo'
  .col-md-8
    .row
      .col-md-12#menu
        table width='100%'
          tr
            - Menu.all.each do |m|
              - if m.published
                td: a.menu-link href='#{m.url}' = m.title
            /td
              a.menu-link href='#{root_url}' Главная
            /- Page.all.each do |page|
              - if page.published
                td
                  a.menu-link href='#{page_url(page)}' = page.title

    hr.min

    .row
      .col-md-7.col-lg-8
        table#autos-list
          - @auto_brands.each_with_index do |brand, i|
            tr
              - if i == 0
                td = image_tag brand.image_32
              - else
                td = image_tag brand.image_32

              - if i == 0
                td.t-j
                  a> href='#{auto_url(Auto.find_by_name('T5').id)}' style='display: block; width: 100%;'
                    button.btn.btn-sm.btn-info style='width: 100%; font-size: 15px;' Multivan, Caravelle, Transporter
                  /br
                  - brand.autos.each do |auto|
                    a> href='#{auto_url(auto.id)}'
                      - if brand.name == 'Volkswagen'
                        button.btn.btn-xs.btn-info = auto.name
                      - if brand.name == 'Skoda'
                        button.btn.btn-xs.btn-success = auto.name
                      - if brand.name == 'Seat'
                        button.btn.btn-xs.btn-danger = auto.name

              - else
                td
                  - brand.autos.each do |auto|
                    a> href='#{auto_url(auto.id)}'
                      - if brand.name == 'Volkswagen'
                        button.btn.btn-xs.btn-info = auto.name
                      - if brand.name == 'Skoda'
                        button.btn.btn-xs.btn-success = auto.name
                      - if brand.name == 'Seat'
                        button.btn.btn-xs.btn-danger = auto.name


      .col-md-5.col-lg-4
        #telefon
          h6.t-r
            a.pointer  data-toggle="modal" data-target="#reception"
              i.fa.fa-envelope-o>
              | Обратная связь
          h3.pull-right style='margin: 0px;'
            span> style='font-size: 15px'
              span.fa.fa-phone.fa-lg>
              |+7 (967)
            |121-5-212
        .clearfix
        #operation-time.pull-right
          small.fa.fa-clock-o>
          small с 9:00 до 22:00
        .clearfix
        br
        form accept-charset="UTF-8" action="/items" method="get"
          .input-group
            div style="display:none"
              input name="utf8" type="hidden" value="✓"
            input.form-control type="text" id="search" name="search" placeholder='Поиск' autocomplete="off"
              span.input-group-btn
                button.btn.btn-default type="submit" value="Search"
                  i.fa.fa-search.fa-lg
                  span style='color: transparent' .
              #search_results

hr#header-shadow

app/views/partials/_items.html.slim
#items

  - if xxx.any?
    / SEARCH
    - if params[:search]
      h4 По Вашему запросу "#{params[:search]}" #{Russian.p(xxx.count, 'найден', 'найдено', 'найдено')} #{xxx.count} #{Russian.p(xxx.count, 'товар', 'товара', 'товаров')}
      hr
    / SEARCH
    / Название каталока
    - if controller_name == 'catalogs' && params[:id]
      h4 = Catalog.find(params[:id]).name
      hr
    - elsif params[:catalog_id]
      h4 = Catalog.find(params[:catalog_id]).name
      hr
    / Название каталока
    - if params[:promo]
      h4 Товары со скидкой
      hr

  - else
    - if controller_name == 'items' && action_name == 'index'
      h4.t-c Извините! По вашему запросу "#{params[:search]}" ничего не найдено
    - else
      h4.t-c Нет товаров для отображения...



  - if xxx.any?
    - xxx.each do |item|
      .cool
        table#item
          tr
            td width='100%'
              .pull-left
                - if item.item_attachments.any?
                  a.thumbnail.item-img href='#{params[:controller] == 'autos' ? auto_item_url(params[:id], item) : item_url(item)}'
                    = image_tag(item.item_attachments.first.image.small_thumb)


              a href='#{params[:controller] == 'autos' ? auto_item_url(params[:id], item) : item_url(item)}'
                b = item.name
              br
              small = item.description
            td style='vertical-align:top'
              - if item.old_price?
                .price_block.btn-group
                  a type="button" class="btn btn-danger large-promo t-r" href='#{params[:controller] == 'autos' ? auto_item_url(params[:id], item) : item_url(item)}'
                    span.fa.fa-shopping-cart.fa-lg>
                    = number_to_currency(item.price, locale: :ru)
                    br
                    /hr.one_border.min
                    small style='text-decoration:line-through; color: #505050; text-shadow:none; '
                      = number_to_currency(item.old_price, locale: :ru)
                  a data-item='#{item.id}' type="button" class="favorite_btn btn btn-danger #{session[:favorite_items].include?(item.id) ? 'remove_from_favorites' : 'add_to_favorites' }"
                    i.fa.fa-star class="#{'in_favorites' if session[:favorite_items].include?(item.id)}"
              - else
                .price_block.btn-group
                  a type="button" class="btn btn-warning large-promo t-r" href='#{params[:controller] == 'autos' ? auto_item_url(params[:id], item) : item_url(item)}' style='padding-top: 14px'
                    span.fa.fa-shopping-cart.fa-lg>
                    = number_to_currency(item.price, locale: :ru)
                    br
                    /hr.one_border.min
                    small style='text-decoration:line-through; color: #505050; text-shadow:none; '
                      = number_to_currency(item.old_price, locale: :ru)
                  a data-item='#{item.id}' type="button" class="favorite_btn btn btn-warning #{session[:favorite_items].include?(item.id) ? 'remove_from_favorites' : 'add_to_favorites' }"
                    i.fa.fa-star class="#{'in_favorites' if session[:favorite_items].include?(item.id)}"



        br
        .row
          .col-md-12
            table.custom
              tr
                td
                  small: small Товар для:
                  - if item.generations.any?
                    - auto_name = ''
                    - x = 0
                    - item.generations.order('auto_id').each do |g|
                      - if g.auto.name != auto_name && x < 5
                        - auto_name = g.auto.name
                        a#item_autos.is_popover_auto.small href='#{auto_url(g.auto)}' data-trigger='hover' data-placement="top" data-toggle="popover" data-container='body' data-content="#{get_generations_html(item.id, g.auto.id).html_safe}" type="button"
                          button.btn.btn-default.btn-xs
                            =' image_tag(g.auto.brand.image, style:"margin: -2 0 0 0;")
                            = auto_name
                            - x += 1
                      - if x == 5
                        - x = 8
                        small>: small>: a.btn.btn-link.btn-xs.muted_link href='#{item_url(item)}' Всего #{item.generations.count} #{Russian::pluralize(item.generations.count, 'модель', 'модели', 'моделей')}



                td
                  - unless item.catalog.blank?
                    - if params[:controller] == 'autos'
                      a#item_autos.btn.btn-link.btn-xs.muted_link.pull-right href='#{catalog_auto_url(item.catalog, params[:id])}'
                        i.fa.fa-tags>
                        = item.catalog.name
                    - elsif params[:controller] == 'catalogs'
                      a#item_autos.btn.btn-link.btn-xs.muted_link.pull-right href='#{catalog_url(item.catalog.id)}'
                        i.fa.fa-tags>
                        = item.catalog.name


        - if admin_user_signed_in?
          .row
            .col-md-12.t-r
              .panel.panel-default
                .panel-body
                  span>
                    /- if item.catalog
                      = item.catalog.id
                    - if item.catalog
                      = select_tag :catalog_id, grouped_options_for_select(grouped_options, item.catalog.id), class: 'catalog_post', 'data-id' => "#{item.id}"
                    - else
                      = select_tag :catalog_id, grouped_options_for_select(grouped_options, nil, prompt: 'Выберите категорию...'), class: 'catalog_post', 'data-id' => "#{item.id}"
                    /= select_tag :catalog_id, grouped_options_for_select(grouped_options, selected: "#{item.catalog.id if item.catalog }", :options => {:prompt => 'asdasd'}), class: 'catalog_post', 'data-id' => "#{item.id}"


                    /= semantic_nested_form_for [:admin, item], :remote => true do |f|
                      = f.select :catalog_id, grouped_options_for_select(grouped_options)

                  span.muted> ||

                  span<
                    a< href='#{edit_admin_item_url(item)}'
                      .btn.btn-danger.btn-xs.pull-right Редактировать


        - if item != xxx.last
          hr
    - if defined?(paginating) && paginating == true
      .t-c
        = paginate xxx

app/views/partials/_reception.html.slim
#reception.modal.fade aria-hidden="true" aria-labelledby="myModalLabel" role="dialog" tabindex="-1"
  .modal-dialog
    .modal-content
      .modal-header
        button.close aria-hidden="true" data-dismiss="modal" type="button"  &times;
        h4#myModalLabel.modal-title Форма отправки сообщения
      .modal-body
        p.t-c: b.notice.text-danger
        = form_for(@reception, remote: true, :html => { :class => 'form-horizontal', :role => 'form', :style => 'margin-bottom: 0;' }) do |f|
          .form-group
            label.col-sm-2.control-label for="reception_email"
              |Email
              b.text-danger> *
            .col-sm-10
              = f.text_field :email, :class => 'form-control', :placeholder=>"Email"

          .form-group
            label.col-sm-2.control-label for="reception_name"
              |Имя
              b.text-danger> *
            .col-sm-10
              = f.text_field :name, :class => 'form-control', :placeholder=>"Ваше имя"

          .form-group
            label.col-sm-2.control-label for="reception_phone"  Телефон
            .col-sm-10
              = f.text_field :phone, :class => 'form-control', :placeholder=>"Телефон"

          .form-group
            label.col-sm-2.control-label for="reception_message"
              |Сообщение
              b.text-danger> *
            .col-sm-10
              = f.text_area :message, :class => 'form-control', :placeholder=>"Введите Ваше сообщение..."

          /= show_simple_captcha

          .modal-footer
            button.btn.btn-default data-dismiss="modal" type="button"  Отмена
            = f.submit 'ОТПРАВИТЬ', :class => 'btn btn-primary'
            /button#reception_submit.btn.btn-primary type="button"  ОТПРАВИТЬ

app/views/partials/_widget_favorites.html.slim
#favorites class='#{'hidden' if session[:favorite_items].blank?}'
  hr
  h4 Избранное
  table
    - if !session[:favorite_items].blank?
      - session[:favorite_items].try(:each) do |item|
        - item = Item.find(item)
        tr id='item_row-#{item.id}' valign="middle"
          td: a.tr.remove_from_favorites remote='true' href='javascript:void(0)' data-item='#{item.id}': img.small-img height='40' src="#{item.item_attachments.any? ? item.item_attachments.first.image.small_thumb : '/assets/item_no_image.png'}"
          td: small: a href='#{item_path(item)}': small = item.name

app/views/partials/_widget_last_news.html.slim
- posts = Post.limit(5)
- if posts
  br
  #widget_last_news
    h4 Наши новости
    - posts.each do |post|
      h6
        i.fa.fa-angle-double-right>
        a href='#{post_url(post)}' = post.title

    .t-r: small: a.btn.btn-default.btn-xs href='#{posts_url}' Все новости

app/views/partials/_widget_last_viewed.html.slim
- unless session[:items].blank? || session[:items] == [nil]
  #widget_last_viewed
    hr
    h4 Просмотренные товары
    .row
      - if session[:items].any?
        - session[:items].each do |item|
          - unless item.nil?
            - unless Item.exists?(:id => item)
              - session[:items] = []
            - else
              - i = Item.find(item)
              .col-md-3.col-sm-2.col-xs-3
                a.is_tooltip.thumbnail href='#{item_url(i)}' data-placement="top" data-toggle="tooltip" title=(i.name) type="button"
                  - if i.item_attachments.any?
                    img src="#{i.item_attachments.first.image.small_thumb}"
                  - else
                    = image_tag('item_no_image.png')

app/views/simple_captcha/_simple_captcha.erb
<style type="text/CSS">
  .simple_captcha{border: 1px solid #ccc; padding: 5px !important;}
  .simple_captcha,
  .simple_captcha div{display: table;}
  .simple_captcha .simple_captcha_field,
  .simple_captcha .simple_captcha_image{
    border: 1px solid #ccc;
    margin: 0px 0px 2px 0px !important;
    padding: 0px !important;
  }
  .simple_captcha .simple_captcha_image img{
    margin: 0px !important;
    padding: 0px !important;
    width: 110px !important;
  }
  .simple_captcha .simple_captcha_label{font-size: 12px;}
  .simple_captcha .simple_captcha_field input{
    width: 150px !important;
    font-size: 16px;
    border: none;
    background-color: #efefef;
  }
</style>

<div class='simple_captcha'>
  <div class='simple_captcha_image'>
    <%= simple_captcha_options[:image] %>
  </div>
  
  <div class='simple_captcha_field'>
    <%= simple_captcha_options[:field] %>
  </div>
  
  <div class='simple_captcha_label'>
    <%= simple_captcha_options[:label] %>
  </div>
</div>